name: CI

on: [push]
jobs:
  test:
    strategy:
      matrix:
        architecture: [x64]
        database: [postgresql]
        extension: [core, dragonfly, images, pages, resources]
        ruby: ['2.6.x', '2.5.x', '2.4.x']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1.0.0
      with:
        architecture: ${{ matrix.architecture }}
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/checkout@v1
    - run: bundle install --without development
    - run: bin/rake refinery:testing:dummy_app
    - run: bin/rspec ${{ matrix.extension }}/spec
      env:
        BUNDLE_JOBS: 4
        CI: true
        DB: ${{ matrix.database }}
        PGHOST: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGUSER: postgres

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432

