name: CI

on: [push]
jobs:
  test:
    strategy:
      matrix:
        architecture: [x64]
        database: [postgresql]
        extension: [core, dragonfly, images, pages, resources]
        ruby: ['2.6.x']
      fail-fast: false
      max-parallel: 10
    runs-on: ubuntu-latest
    name: ${{ matrix.extension }} ${{ matrix.ruby }} ${{ matrix.database }}
    steps:
    - uses: actions/setup-ruby@v1.0.0
      with:
        architecture: ${{ matrix.architecture }}
        ruby-version: ${{ matrix.ruby }}
        version: ${{ matrix.ruby }}
    - uses: actions/checkout@v1
    - run: sudo apt-get install libpq-dev libmysqlclient-dev libsqlite3-dev -y
    - run: bundle install --without development
      env:
        BUNDLE_JOBS: 4
        CI: true
    - run: |
        bin/rake refinery:testing:dummy_app
        bin/rspec ${{ matrix.extension }}/spec
      env:
        CI: true
        DB: ${{ matrix.database }}
        PG_HOST: localhost
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports[5432] }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

