name: CI

on: [push]

jobs:
  postgres:
    runs-on: ubuntu-latest
    container: 
      image: ruby:2.6-alpine

    steps:
    - uses: actions/checkout@v1
    - run: apk add git g++ tzdata sqlite-dev mysql-dev postgresql-dev postgresql-client nodejs imagemagick
    - run: apk add --virtual .ruby-gemdeps libc-dev gcc libxml2-dev libxslt-dev make
    - run: apk add chromium chromium-chromedriver
    - run: bundle install --without development
    - run: bin/rake refinery:testing:dummy_app
    - run: bin/rspec ./*/spec --format documentation
      env:
        DB: postgresql
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RETRY_COUNT: 3

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
