name: CI

on: [push]

jobs:
  postgres:
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.6-node-browsers

    steps:
    - uses: actions/checkout@v1
    - run: sudo touch Gemfile.lock && sudo chown $(whoami) Gemfile.lock && bundle install --without development
    - run: bin/rake refinery:testing:dummy_app
    - run: bin/rspec ./*/spec --format documentation
      env:
        DB: postgresql
        PGHOST: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGUSER: postgres
        RETRY_COUNT: 3

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
