name: CI

on: [push]

jobs:
  postgres:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker login docker.pkg.github.com --username refinery
    - uses: docker://docker.pkg.github.com/refinery/refinerycms/ci:latest
    - run: bundle install --without development
    - run: bin/rake refinery:testing:dummy_app
    - run: bin/rspec ./*/spec --format documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RETRY_COUNT: 3

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
